# Generated by Django 4.0.4 on 2023-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('model_url', models.CharField(blank=True, default='', max_length=255)),
                ('source_lang', models.CharField(max_length=255)),
                ('destination_lang', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('score', models.FloatField(default=0)),
            ],
        ),
    ]
